### ISSUE TITLE
仅依赖函数二进制进行存在性判断？

### ISSUE THREAD

**Issue by akaganeite** [Qi-Zhan/ps3#3]
您好！我刚开始了解二进制的补丁存在性检测方法。请问您的这个工作有没有可能仅依赖patch所更改的函数二进制(patch,vuln和target)来做补丁存在性检测吗？

**Comment by Qi-Zhan** [comment]
你的意思是只有二进制吗? 那该工作是无法进行测试的, 我们这篇工作主要是针对开源组件复用的场景, 所以预设Patch源代码存在. 如果只有二进制的话, 那么 [BinXray](https://dl.acm.org/doi/abs/10.1145/3395363.3397361) 更符合您的要求

**Comment by akaganeite** [comment]
收到，感谢您的回复！
